SELECT COUNT(*) COUNT FROM (SELECT RIGHT(BIN(GENOTYPE),4) 
                            GENOTYPE FROM ECOLI_DATA) A
 WHERE SUBSTRING(LPAD(A.GENOTYPE,4,'0'),-2,1) = '0' 
 AND (SUBSTRING(LPAD(A.GENOTYPE,4,'0'),-3,1) = '1'
    OR SUBSTRING(LPAD(A.GENOTYPE,4,'0'),-1,1) = '1')
 