-- 코드를 입력하세요
SELECT CRCC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS CRCC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH
ON CRCC.CAR_ID = CRCRH.CAR_ID
WHERE CRCRH.START_DATE LIKE "2022-10%"
AND CRCC.CAR_TYPE LIKE "세단"
GROUP BY CRCC.CAR_ID
ORDER BY CAR_ID DESC;